version: "1.0"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: Hahaton
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#    network_mode: 'host'
    ports:
      - 5432:5432